[package]
name = "crud-file-server"
version = "0.1.0"
authors = ["Emil Rasmus Merzin <rasmusmerzin@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1", features = ["attributes"] }
tide = "0.16"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
surf = "2"
